### ISSUE TITLE
Dependencies missing when using files/fileTree

### ISSUE THREAD

**Issue by Ph3n1x** [excelsior-oss/excelsior-jet-gradle-plugin#12]
I define some dependencies with the help of files(..) or fileTree(..), which is useful for dependencies, which are not published to a maven/gradle repository.

For example I am adding all dependencies under `${project.dir}/libs` with `compile fileTree(dir: 'libs', include: '*.jar')`. These are missing on the classpath and therefor e.g. the `jetTestRun` will throw a NoClassDefFoundError.

**Comment by Ph3n1x** [comment]
See here https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/pull/14

**Comment by pjBooms** [comment]
Hi!

Good catch! It seems we really missed this stuff.
Your PR is better to apply to our [dependency management](https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/tree/azhidkov/dependency-management#dependencies-management) release, but it cannot be applied as is, because we refactored the API and the plugin for the release regarding this stuff. But I think we need to incorporate your PR anyway to it though it will require some changes in core dependency management logic. Thank you anyway for PR!

**Comment by Ph3n1x** [comment]
No problem, I am glad I could help you!
